= Users
REST API обеспечивающий работу с таким ресурсом как пользователи.

== Endpoints
* */UsersAPI/v1/CreateUser* - Создать пользователя. POST метод, в теле которого передается объект с полями;
* */UsersAPI/v1/CreateUsers* - Создать несколько пользователей. POST метод, в теле которого передается массив объектов;
* */UsersAPI/v1/GetUserById/{id}* - Получить пользователя по id. GET метод, в строке запроса которого передается числовое значение.
* */UsersAPI/v1/GetUserByLogin/{login}* - Получить пользователя по login. GET метод, строке запроса которого передается строка.
* */UsersAPI/v1/GetUsersById* - Получить пользователей по id. GET метод, в строке запроса которого передаются числовые значения.
* */UsersAPI/v1/GetFullFieldUser/{id}* - Получить пользователя со всеми полями по id. GET метод, в строке запроса которого передается числовое значение. 
* */UsersAPI/v1/DeleteUser/{id}* - Удалить пользователя по id. DELETE метод, в строке запроса которого передается числовое значение.
* */UsersAPI/v1/DeleteUsers* - Удалить множество пользователей по id. DELETE метод, в тело которого передается массив числовых значений.
* */UsersAPI/v1/UpdateUser/{id}* - Изменить поля пользователя. PUT метод, в строке запроса которого передается числовое значение и в теле передается новые значения полей.
* */UsersAPI/v1/UpdateUserName/{id}&{name}* - Изменить имя пользователя по id. PUT метод, в строке запроса которого передается числовое значение(id) и строка(name).